import type { Product } from "../types/product";

export const products: Product[] = [
  {
    id: 1,
    name: "Justice Tocat",
    description: "Stand for what's right with this heroic Octocat",
    price: 29.99,
    image: "/images/products/justicetocat.jpg",
  },
  {
    id: 2,
    name: "Dino Tocat",
    description: "A prehistoric twist on your favorite Octocat",
    price: 34.99,
    image: "/images/products/dinotocat.png",
  },
  {
    id: 3,
    name: "Female Coder Tocat",
    description: "Celebrating women in tech",
    price: 32.99,
    image: "/images/products/femalecodertocat.png",
  },
  {
    id: 4,
    name: "Jetpack Tocat",
    description: "Blast off to new coding heights",
    price: 39.99,
    image: "/images/products/jetpacktocat.png",
  },
  {
    id: 5,
    name: "Surf Tocat",
    description: "Ride the waves of innovation",
    price: 31.99,
    image: "/images/products/surftocat.png",
  },
  {
    id: 6,
    name: "Mona The Riveter Tocat",
    description: "We can code it!",
    price: 33.99,
    image: "/images/products/mona-the-rivetertocat.png",
  },
  {
    id: 7,
    name: "Terracotta Cat",
    description: "An earthy, artistic take on Octocat",
    price: 28.99,
    image: "/images/products/Terracottocat_Single.png",
  },
  {
    id: 8,
    name: "Original Octocat",
    description: "The classic that started it all",
    price: 35.99,
    image: "/images/products/original.png",
  },
  {
    id: 9,
    name: "Manufacture Tocat",
    description: "Built to last, crafted with care",
    price: 36.99,
    image: "/images/products/manufacturetocat.png",
  },
  {
    id: 10,
    name: "Bouncer Cat",
    description: "Security expert and friendly guardian",
    price: 33.99,
    image: "/images/products/bouncercat.png",
  },
  {
    id: 11,
    name: "Skate Tocat",
    description: "Shred the code, grind the bugs",
    price: 32.99,
    image: "/images/products/skatetocat.png",
  },
  {
    id: 12,
    name: "Vinyl Tocat",
    description: "For those who appreciate the classics",
    price: 37.99,
    image: "/images/products/vinyltocat.png",
  },
  {
    id: 13,
    name: "Cherry On Top O Cat",
    description: "The perfect finishing touch",
    price: 30.99,
    image: "/images/products/cherryontop-o-cat.png",
  },
  {
    id: 14,
    name: "Oktobercat",
    description: "Celebrate in style",
    price: 34.99,
    image: "/images/products/oktobercat.png",
  },
  {
    id: 15,
    name: "Welcome Tocat",
    description: "A friendly greeting for all",
    price: 29.99,
    image: "/images/products/welcometocat.png",
  },
  {
    id: 16,
    name: "Yogi Tocat",
    description: "Find your inner peace while coding",
    price: 31.99,
    image: "/images/products/yogitocat.png",
  },
  {
    id: 17,
    name: "Sponsor Tocat",
    description: "Support open source in style",
    price: 38.99,
    image: "/images/products/sponsortocat.png",
  },
  {
    id: 18,
    name: "Inflato Cat",
    description: "Full of hot air and ready to code",
    price: 35.99,
    image: "/images/products/inflatocat.png",
  },
  {
    id: 19,
    name: "Red Polo Octocat",
    description: "Classic style meets modern coding",
    price: 32.99,
    image: "/images/products/red-polo.png",
  },
  {
    id: 20,
    name: "Professor Tocat",
    description: "Wisdom and knowledge personified",
    price: 36.99,
    image: "/images/products/Professortocat_v2.png",
  },
];
