import { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Professor Octocat',
    description: 'The scholarly Octocat teaching the ways of Git',
    price: 29.99,
    image: '/images/products/Professortocat_v2.png',
    category: 'Education',
  },
  {
    id: '2',
    name: 'Terracotta Octocat',
    description: 'A classic Octocat figure for your desk',
    price: 24.99,
    image: '/images/products/Terracottocat_Single.png',
    category: 'Classic',
  },
  {
    id: '3',
    name: 'Bouncer Octocat',
    description: 'The security expert keeping your repos safe',
    price: 34.99,
    image: '/images/products/bouncercat.png',
    category: 'Security',
  },
  {
    id: '4',
    name: 'Cherry on Top Octocat',
    description: 'Sweet and delightful Octocat with a cherry',
    price: 27.99,
    image: '/images/products/cherryontop-o-cat.png',
    category: 'Fun',
  },
  {
    id: '5',
    name: 'Dino Octocat',
    description: 'Prehistoric coding companion',
    price: 31.99,
    image: '/images/products/dinotocat.png',
    category: 'Fun',
  },
  {
    id: '6',
    name: 'Female Coder Octocat',
    description: 'Celebrating women in tech',
    price: 29.99,
    image: '/images/products/femalecodertocat.png',
    category: 'Diversity',
  },
  {
    id: '7',
    name: 'Inflato Octocat',
    description: 'Balloon-style Octocat ready to float',
    price: 22.99,
    image: '/images/products/inflatocat.png',
    category: 'Fun',
  },
  {
    id: '8',
    name: 'Jetpack Octocat',
    description: 'Blast off with this futuristic Octocat',
    price: 39.99,
    image: '/images/products/jetpacktocat.png',
    category: 'Tech',
  },
  {
    id: '9',
    name: 'Justice Octocat',
    description: 'Fighting for code justice everywhere',
    price: 35.99,
    image: '/images/products/justicetocat.jpg',
    category: 'Hero',
  },
  {
    id: '10',
    name: 'Manufacture Octocat',
    description: 'Industrial-strength coding power',
    price: 33.99,
    image: '/images/products/manufacturetocat.png',
    category: 'Industry',
  },
  {
    id: '11',
    name: 'Mona the Riveter',
    description: 'We can code it!',
    price: 32.99,
    image: '/images/products/mona-the-rivetertocat.png',
    category: 'Classic',
  },
  {
    id: '12',
    name: 'Oktobercat',
    description: 'Celebrating Oktoberfest in style',
    price: 28.99,
    image: '/images/products/oktobercat.png',
    category: 'Seasonal',
  },
];

export const coupons = [
  { code: 'SAVE10', discountPercentage: 10 },
  { code: 'SAVE20', discountPercentage: 20 },
  { code: 'WELCOME15', discountPercentage: 15 },
];
